In [1]:
#pip install tensorflow

In [2]:
#Word Encoding : Convert text into Number, Assign unique number to each unique word

In [3]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.preprocessing.text import Tokenizer

In [4]:
sample_stentence=["It is a sunny day",
                  "It is a Rainy Day",
                  "It is Cloudy day"]

In [5]:
tokenizer=Tokenizer(num_words=100, # depends on the size of text data, If 100 will pick top 100 high prequent word and tokenize them
                   )

In [6]:
tokenizer.fit_on_texts(sample_stentence)

In [7]:
each_wrd_index=tokenizer.word_index

In [8]:
print(each_wrd_index)

{'it': 1, 'is': 2, 'day': 3, 'a': 4, 'sunny': 5, 'rainy': 6, 'cloudy': 7}


Create Sequence

In [9]:
#Convert sentences into number
sequences=tokenizer.texts_to_sequences(sample_stentence)


In [10]:
print(each_wrd_index)
print(sample_stentence)
print(sequences)

{'it': 1, 'is': 2, 'day': 3, 'a': 4, 'sunny': 5, 'rainy': 6, 'cloudy': 7}
['It is a sunny day', 'It is a Rainy Day', 'It is Cloudy day']
[[1, 2, 4, 5, 3], [1, 2, 4, 6, 3], [1, 2, 7, 3]]


Tokenizing New data using Same Tokenizer

In [11]:
new_sentences=["will be raining today","It is a pleaant day"]

In [12]:
new_sequence=tokenizer.texts_to_sequences(new_sentences)
print(new_sentences)
print(new_sequence)

['will be raining today', 'It is a pleaant day']
[[], [1, 2, 4, 3]]


In [13]:
tokenizer=Tokenizer(num_words=100,oov_token="<oov>")
tokenizer.fit_on_texts(sample_stentence)
new_word_index=tokenizer.word_index

In [14]:
new_sequence=tokenizer.texts_to_sequences(new_sentences)
print(new_word_index)
print(new_sequence)

{'<oov>': 1, 'it': 2, 'is': 3, 'day': 4, 'a': 5, 'sunny': 6, 'rainy': 7, 'cloudy': 8}
[[1, 1, 1, 1], [2, 3, 5, 1, 4]]


Padding the Sequence

In [15]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [16]:
sample_stentence=["It is a sunny day",
                  "It is a Rainy Day",
                  "It is Cloudy day",
               "will be raining today","It is a pleaant day"]

In [17]:
tokenizer=Tokenizer(num_words=100,oov_token="<oov>")
tokenizer.fit_on_texts(sample_stentence)
new_sequence=tokenizer.texts_to_sequences(sample_stentence)

In [18]:
padded_seq=pad_sequences(new_sequence)

In [19]:
print(each_wrd_index)
print(sample_stentence)
print(new_sequence)
print(padded_seq)

{'it': 1, 'is': 2, 'day': 3, 'a': 4, 'sunny': 5, 'rainy': 6, 'cloudy': 7}
['It is a sunny day', 'It is a Rainy Day', 'It is Cloudy day', 'will be raining today', 'It is a pleaant day']
[[2, 3, 5, 6, 4], [2, 3, 5, 7, 4], [2, 3, 8, 4], [9, 10, 11, 12], [2, 3, 5, 13, 4]]
[[ 2  3  5  6  4]
 [ 2  3  5  7  4]
 [ 0  2  3  8  4]
 [ 0  9 10 11 12]
 [ 2  3  5 13  4]]


Customising Padded Squence

In [20]:
padded_sequence=pad_sequences(new_sequence,
                              padding="post",
                              maxlen=4,
                              truncating="post")

In [21]:
print(padded_sequence)

[[ 2  3  5  6]
 [ 2  3  5  7]
 [ 2  3  8  4]
 [ 9 10 11 12]
 [ 2  3  5 13]]


In [22]:
import pandas as pd

In [87]:
data=pd.read_json("./Sarcasm_Headlines_Dataset.json",lines=True)

In [88]:
data.head(5)

article_link  \
0  https://www.huffingtonpost.com/entry/versace-b...   
1  https://www.huffingtonpost.com/entry/roseanne-...   
2  https://local.theonion.com/mom-starting-to-fea...   
3  https://politics.theonion.com/boehner-just-wan...   
4  https://www.huffingtonpost.com/entry/jk-rowlin...   

                                            headline  is_sarcastic  
0  former versace store clerk sues over secret 'b...             0  
1  the 'roseanne' revival catches up to our thorn...             0  
2  mom starting to fear son's web series closest ...             1  
3  boehner just wants wife to listen, not come up...             1  
4  j.k. rowling wishes snape happy birthday in th...             0

In [89]:
headlines=list(data["headline"])
labels=list(data["is_sarcastic"])

In [90]:
tokenizer=Tokenizer(oov_token="<oov>")
tokenizer.fit_on_texts(headlines)

In [91]:
headline_index=tokenizer.word_index

In [92]:
# print(headline_index)

In [93]:
# Create Padded Sequence
headline_sequence=tokenizer.texts_to_sequences(headlines)
padded_headline_sequence=pad_sequences(headline_sequence,
                                      maxlen=1000,
                                      padding="post",
                                      truncating="post")

In [30]:
padded_headline_sequence

array([[  308, 15115,   679, ...,     0,     0,     0],
       [    4,  8435,  3338, ...,     0,     0,     0],
       [  145,   838,     2, ...,     0,     0,     0],
       ...,
       [10735,     9,    68, ...,     0,     0,     0],
       [ 1541,   392,  4164, ...,     0,     0,     0],
       [29656,  1647,     6, ...,     0,     0,     0]], dtype=int32)

Word Embedding for Setntimnt Analysis

In [31]:
import numpy as np
import pandas as pd
import tensorflow_datasets as tfds
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [94]:
data,info=tfds.load("imdb_reviews",with_info=True,as_supervised=True)

In [95]:
# data

In [96]:
train_data,test_data=data["train"],data["test"]

In [105]:
train_sentences=[]
train_labels=[]

test_sentences=[]
test_labels=[]

for s_sentence,s_label in train_data:
    train_sentences.append(str(s_sentence.numpy().decode("utf8")))
    train_labels.append(s_label.numpy())

for s_sentence,s_label in test_data:
    test_sentences.append(str(s_sentence.numpy().decode("utf8")))
    test_labels.append(s_label.numpy())

2024-08-30 15:23:11.444803: I tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


In [106]:
len(train_sentences),len(train_labels),len(test_sentences),len(test_labels)

(25000, 25000, 25000, 25000)

In [107]:
train_labels=np.array(train_labels)
test_labels=np.array(test_labels)

Data Prearation

In [108]:
vocab_size=10000
embedding_dims=16
max_length=150
trun_type="post"
oov_tok="<oov>"

In [109]:
tokenizer=Tokenizer(num_words=vocab_size,oov_token=oov_tok)
tokenizer.fit_on_texts(train_sentences)
train_word_index=tokenizer.index_word

In [110]:
train_sequence=tokenizer.texts_to_sequences(train_sentences)
train_padded=pad_sequences(train_sequence,maxlen=max_length,truncating=trun_type)

test_sequence=tokenizer.texts_to_sequences(test_sentences)
test_padded=pad_sequences(test_sequence,maxlen=max_length)


In [103]:
reverse_word_index = dict([(value, key) for (key, value) in train_word_index.items()])

def decode_review(text):
    return ' '.join([reverse_word_index.get(i, '?') for i in text])

print(train_sentences[1])
print(train_padded[1])
print(decode_review(train_padded[1]))

I have been known to fall asleep during films, but this is usually due to a combination of things including, really tired, being warm and comfortable on the sette and having just eaten a lot. However on this occasion I fell asleep because the film was rubbish. The plot development was constant. Constantly slow and boring. Things seemed to happen, but with no explanation of what was causing them or why. I admit, I may have missed part of the film, but i watched the majority of it and everything just seemed to happen of its own accord without any real concern for anything else. I cant recommend this film at all.
[   0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0   11   26   75  571
    6  805 2354  313  106   19   12    7  629  686    6    4 2219    5
  181  584   64 1454  110 2263    3 3951   21    2    1    3  258   41
 4677    4  174  188   21  

In [41]:
reverse_word_index=dict([(value,key) for (key,value) in train_word_index.items()])

In [42]:
def decode_review(text):
    return " ".join([reverse_word_index.get(i,'?') for i in text])

In [43]:
print(train_sentences[12])
print(train_padded[12])
print(decode_review(train_padded[12]))

This 1984 version of the Dickens' classic `A Christmas Carol,' directed by Clive Donner, stars George C. Scott as Ebenezer Scrooge. By this time around, the challenge for the filmmaker was to take such familiar material and make it seem fresh and new again; and, happily to say, with this film Donner not only met the challenge but surpassed any expectations anyone might have had for it. He tells the story with precision and an eye to detail, and extracts performances from his actors that are nothing less than superlative, especially Scott. One could argue that the definitive portrayal of Scrooge-- one of the best known characters in literary fiction, ever-- was created by Alastair Sim in the 1951 film; but I think with his performance here, Scott has now achieved that distinction. There is such a purity and honesty in his Scrooge that it becomes difficult to even consider anyone else in the role once you've seen Scott do it; simply put, he IS Scrooge. And what a tribute it is to such a 

Defining Neural Network

In [44]:
model=tf.keras.Sequential(
    [tf.keras.layers.Embedding(vocab_size,embedding_dims),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(6,activation="relu"),
    tf.keras.layers.Dense(1,activation="sigmoid")]
)

In [45]:
model.compile(loss="binary_crossentropy",optimizer="adam",metrics=["accuracy"])

In [46]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

model training 

In [47]:
num_epochs=10
model.fit(train_padded,train_labels,epochs=num_epochs,validation_data=(test_padded,test_labels))

Epoch 1/10
782/782 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.6439 - loss: 0.6005 - val_accuracy: 0.8561 - val_loss: 0.3257
Epoch 2/10
782/782 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9040 - loss: 0.2438 - val_accuracy: 0.8473 - val_loss: 0.3555
Epoch 3/10
782/782 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9661 - loss: 0.1180 - val_accuracy: 0.8406 - val_loss: 0.4066
Epoch 4/10
782/782 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9915 - loss: 0.0393 - val_accuracy: 0.8394 - val_loss: 0.4668
Epoch 5/10
782/782 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9984 - loss: 0.0118 - val_accuracy: 0.8401 - val_loss: 0.5376
Epoch 6/10
782/782 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9996 - loss: 0.0040 - val_accuracy: 0.8348 - val_loss: 0.6193
Epoch 7/10
782/782 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 1.0000 - loss: 0.0015 - val_accuracy: 0.8444 - val_loss: 0.6226
Epoch 8/10
782/782 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9999 - loss: 7.6570e-04 - val_accuracy

In [48]:
l1=model.layers[0]

In [49]:
weights=l1.get_weights()[0] 

In [50]:
print(weights.shape)

(10000, 16)


In [51]:
print(weights)

[[ 0.00342315 -0.02873652 -0.02317829 ...  0.01717788  0.01050576
   0.00590531]
 [ 0.00186289 -0.00641223 -0.1064241  ...  0.11152837  0.010881
   0.04139196]
 [-0.02761421 -0.01409279 -0.06043289 ...  0.04221026  0.0426674
   0.08965921]
 ...
 [-0.0341365   0.01604268 -0.10272564 ... -0.13017605  0.15796998
  -0.13821319]
 [-0.05898974 -0.01386654 -0.11921073 ... -0.02815987  0.07929522
  -0.02766588]
 [ 0.11017534 -0.05797466 -0.11416346 ... -0.04410853  0.16170958
  -0.00369502]]


Projecting Embedding on Tensorflow projector

In [54]:
import numpy as np
import pandas as d
import tensorflow_datasets as tfds
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [57]:
data,info=tfds.load("imdb_reviews",with_info=True, as_supervised=True)

In [77]:
# reverse_word_index

In [70]:
reverse_reverse_word_index={}
for s_letter in reverse_word_index:
    reverse_reverse_word_index[reverse_word_index[s_letter]]=s_letter

In [71]:
reverse_reverse_word_index

{1: '<oov>',
 2: 'the',
 3: 'and',
 4: 'a',
 5: 'of',
 6: 'to',
 7: 'is',
 8: 'br',
 9: 'in',
 10: 'it',
 11: 'i',
 12: 'this',
 13: 'that',
 14: 'was',
 15: 'as',
 16: 'for',
 17: 'with',
 18: 'movie',
 19: 'but',
 20: 'film',
 21: 'on',
 22: 'not',
 23: 'you',
 24: 'are',
 25: 'his',
 26: 'have',
 27: 'he',
 28: 'be',
 29: 'one',
 30: 'all',
 31: 'at',
 32: 'by',
 33: 'an',
 34: 'they',
 35: 'who',
 36: 'so',
 37: 'from',
 38: 'like',
 39: 'her',
 40: 'or',
 41: 'just',
 42: 'about',
 43: "it's",
 44: 'out',
 45: 'if',
 46: 'has',
 47: 'some',
 48: 'there',
 49: 'what',
 50: 'good',
 51: 'more',
 52: 'when',
 53: 'very',
 54: 'up',
 55: 'no',
 56: 'time',
 57: 'she',
 58: 'even',
 59: 'my',
 60: 'would',
 61: 'which',
 62: 'only',
 63: 'story',
 64: 'really',
 65: 'see',
 66: 'their',
 67: 'had',
 68: 'can',
 69: 'were',
 70: 'me',
 71: 'well',
 72: 'than',
 73: 'we',
 74: 'much',
 75: 'been',
 76: 'bad',
 77: 'get',
 78: 'will',
 79: 'do',
 80: 'also',
 81: 'into',
 82: 'people',
 8

In [72]:
vocab_size

10000

In [73]:
import io

vectors_file=io.open("vectoprs.tsv","w", encoding="utf-8")
meta_file=io.open("meta.tsv","w",encoding="utf-8")

for index in range(1, vocab_size):
    word=reverse_reverse_word_index[index]
    embedding=weights[index]
    meta_file.write(word+"\n")
    vectors_file.write("\t".join(str(x) for x in embedding)+"\n")


In [ ]:
# Upload this two file to Tensorflow Projector

Build NLP Classifier

In [74]:
import numpy as np
import pandas as d
import tensorflow_datasets as tfds
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [75]:
data=pd.read_json("./Sarcasm_Headlines_Dataset.json",lines=True)

In [76]:
data.head()

article_link  \
0  https://www.huffingtonpost.com/entry/versace-b...   
1  https://www.huffingtonpost.com/entry/roseanne-...   
2  https://local.theonion.com/mom-starting-to-fea...   
3  https://politics.theonion.com/boehner-just-wan...   
4  https://www.huffingtonpost.com/entry/jk-rowlin...   

                                            headline  is_sarcastic  
0  former versace store clerk sues over secret 'b...             0  
1  the 'roseanne' revival catches up to our thorn...             0  
2  mom starting to fear son's web series closest ...             1  
3  boehner just wants wife to listen, not come up...             1  
4  j.k. rowling wishes snape happy birthday in th...             0